# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: true
cache: packages
after_success:
    - Rscript -e 'covr::codecov()'

before_install:
  # load gcc-6 and make it default
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test

install:
  - sudo apt-get install -y gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6
