# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rcpp_wkt_overlaps_cartesian <- function(wktOne, wktTwo) {
    .Call(`_boostgeometry_rcpp_wkt_overlaps_cartesian`, wktOne, wktTwo)
}

rcpp_wkt_area <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_area`, wkt, strategy)
}

rcpp_wkt_buffer_cartesian <- function(wkt, distance, points_per_circle) {
    .Call(`_boostgeometry_rcpp_wkt_buffer_cartesian`, wkt, distance, points_per_circle)
}

rcpp_wkt_centroid <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_centroid`, wkt)
}

rcpp_wkt_clear <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_clear`, wkt)
}

rcpp_wkt_comparable_distance_cartesian <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_comparable_distance_cartesian`, wktFrom, wktTo)
}

rcpp_wkt_comparable_distance_spherical <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_comparable_distance_spherical`, wktFrom, wktTo)
}

rcpp_wkt_comparable_distance_geographic <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_comparable_distance_geographic`, wktFrom, wktTo)
}

rcpp_wkt_convex_hull_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_convex_hull_cartesian`, wkt)
}

rcpp_wkt_correct <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_correct`, wkt, strategy)
}

rcpp_wkt_crosses_cartesian <- function(x, y) {
    .Call(`_boostgeometry_rcpp_wkt_crosses_cartesian`, x, y)
}

rcpp_wkt_crosses_spherical <- function(x, y) {
    .Call(`_boostgeometry_rcpp_wkt_crosses_spherical`, x, y)
}

rcpp_wkt_crosses_geographic <- function(x, y) {
    .Call(`_boostgeometry_rcpp_wkt_crosses_geographic`, x, y)
}

rcpp_wkt_densify_cartesian <- function(wkt, distance) {
    .Call(`_boostgeometry_rcpp_wkt_densify_cartesian`, wkt, distance)
}

rcpp_wkt_densify_spherical <- function(wkt, distance) {
    .Call(`_boostgeometry_rcpp_wkt_densify_spherical`, wkt, distance)
}

rcpp_wkt_densify_geographic <- function(wkt, distance) {
    .Call(`_boostgeometry_rcpp_wkt_densify_geographic`, wkt, distance)
}

rcpp_wkt_difference <- function(wktOne, wktTwo, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_difference`, wktOne, wktTwo, strategy)
}

rcpp_wkt_distance_cartesian <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_distance_cartesian`, wktFrom, wktTo)
}

rcpp_wkt_distance_spherical <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_distance_spherical`, wktFrom, wktTo)
}

rcpp_wkt_distance_geographic <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_distance_geographic`, wktFrom, wktTo)
}

rcpp_wkt_envelope_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_envelope_cartesian`, wkt)
}

rcpp_wkt_envelope_spherical <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_envelope_spherical`, wkt)
}

rcpp_wkt_envelope_geographic <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_envelope_geographic`, wkt)
}

rcpp_wkt_equals_cartesian <- function(wktOne, wktTwo) {
    .Call(`_boostgeometry_rcpp_wkt_equals_cartesian`, wktOne, wktTwo)
}

rcpp_wkt_is_empty <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_is_empty`, wkt, strategy)
}

rcpp_wkt_is_simple <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_is_simple`, wkt, strategy)
}

rcpp_wkt_is_valid <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_is_valid`, wkt, strategy)
}

rcpp_wkt_length_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_length_cartesian`, wkt)
}

rcpp_wkt_length_spherical <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_length_spherical`, wkt)
}

rcpp_wkt_length_geographic <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_length_geographic`, wkt)
}

rcpp_wkt_num_geometries <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_geometries`, wkt)
}

rcpp_wkt_num_interior_rings <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_interior_rings`, wkt)
}

rcpp_wkt_num_points <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_points`, wkt)
}

rcpp_wkt_num_segments <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_num_segments`, wkt)
}

rcpp_wkt_perimeter_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_perimeter_cartesian`, wkt)
}

rcpp_wkt_perimeter_spherical <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_perimeter_spherical`, wkt)
}

rcpp_wkt_perimeter_geographic <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_perimeter_geographic`, wkt)
}

rcpp_wkt_reverse <- function(wkt, strategy) {
    .Call(`_boostgeometry_rcpp_wkt_reverse`, wkt, strategy)
}

rcpp_wkt_simplify_cartesian <- function(wkt, distance) {
    .Call(`_boostgeometry_rcpp_wkt_simplify_cartesian`, wkt, distance)
}

rcpp_wkt_simplify_spherical <- function(wkt, distance) {
    .Call(`_boostgeometry_rcpp_wkt_simplify_spherical`, wkt, distance)
}

rcpp_wkt_touches_cartesian <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_touches_cartesian`, wktFrom, wktTo)
}

rcpp_wkt_touches_spherical <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_touches_spherical`, wktFrom, wktTo)
}

rcpp_wkt_touches_geographic <- function(wktFrom, wktTo) {
    .Call(`_boostgeometry_rcpp_wkt_touches_geographic`, wktFrom, wktTo)
}

rcpp_wkt_unique_cartesian <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_unique_cartesian`, wkt)
}

rcpp_wkt_unique_spherical <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_unique_spherical`, wkt)
}

rcpp_wkt_unique_geographic <- function(wkt) {
    .Call(`_boostgeometry_rcpp_wkt_unique_geographic`, wkt)
}

rcpp_wkt_within_cartesian <- function(x, y) {
    .Call(`_boostgeometry_rcpp_wkt_within_cartesian`, x, y)
}

rcpp_wkt_within_spherical <- function(x, y) {
    .Call(`_boostgeometry_rcpp_wkt_within_spherical`, x, y)
}

rcpp_wkt_within_geographic <- function(x, y) {
    .Call(`_boostgeometry_rcpp_wkt_within_geographic`, x, y)
}

